### ISSUE TITLE
Create afloat pallet

### ISSUE THREAD

**Issue by tlacloc** [hashed-io/hashed-substrate#394]
## Description:

We need to create the Afloat pallet and initialize it using the template. This will enable us to add the required functionality for the Afloat platform and couple it with Fruniques and potentially other marketplaces.

The main reason for this change is to provide a solid foundation for the Afloat platform and ensure that it can function efficiently and effectively.

## Tasks:
- Create the Afloat pallet using the template.
- Initialize the Afloat pallet with the required functionality.
- Couple the Afloat pallet with Fruniques and other marketplaces if needed.
- Test the pallet to ensure accuracy and consistency.

## Expected Outcome:

Once implemented, the Afloat pallet will provide the necessary functionality for the Afloat platform. The initialization process will ensure that the pallet has the required functionality and that it can couple with Fruniques and other marketplaces. This change will ensure that the Afloat platform has a solid foundation and is built on top of a robust and reliable pallet.

**Comment by Dreyhh** [comment]
# Afloat's Legacy Flows

### User-registration Flow

Afloat's Legacy Login Flow uses the following data:

1. First Name (String)

2. Last Name (String)

3. Email (String)

4. State (Select Object)

   e.g: Alabama ('3')

   `3 :{`
       `"id": 3,`
       `"title": "ALABAMA",`
       `"stateAbbreviation": "AL"`
   `}`

Notice that at the moment of registration only one state can be selected and therefore any user will have only one state attached to it's user information.

This is important since it determines what kind(s) of tax credit a user is allowed to enlist for sale.

For example, a user whose state is Alabama can only enlist for sale the following types of tax credit:

`0:{`
    `"id": 4,`
    `"title": "Alabama Economic Development Credit",`
    `"code": "AL_ECONOMIC_DEVELOPMENT_CREDIT",`
    `"displayName": "Land Economic Development Credit",`
    `"taxAuthorityId": 3,`
    `"taxAuthorityTitle": "ALABAMA"`
`},`

`1:{`
    `"id": 5,`
    `"title": "Alabama Historic Property Tax Credit",`
    `"code": "AL_HISTORIC_PROPERTY_TAX_CREDIT",`
    `"displayName": "Historic Property Tax Credit",`
    `"taxAuthorityId": 3,`
    `"taxAuthorityTitle": "ALABAMA"`
`}`

That is, members of this set must have taxAuthorityId  ==  User.state.id.

### New user-registration Flow (Backend)

For the new user registration flow we can do the following:

1. First, we need to create the marketplace for Afloat alongside a designated admin account.

2. When the new user has entered the required data and agreed with the TOS, the frontend should make a call (from the admin account) to the marketplace extrinsic: addAuthorityAfloat(account, authorityType, marketplaceId, userdata)

This assumes we want to allow any user to self-enroll, as is currently enabled in Afloat's legacy flow. If not, we can use the apply-to-marketplace flow.

To implement this, we should add the following structs to the Marketplace pallet:

```rust



pub struct User {
    account_id: AccountId,
    first_name: Vec<u8>,
    last_name: Vec<u8>,
    email: Vec<u8>,
    state: State,
}


pub struct State {
    id: u32,
    title: Vec<u8>,
    state_abbreviation: Vec<u8>,
}


```

Then, we need to define an addAuthorityAfloat extrinsic that, in addition to calling insert_in_auth_market_lists, will also add the (AccountId, userdata) key-value pair to a new StorageMap (let's call it UsersAfloat). This map can later be queried by the frontend to retrieve user information.
