### ISSUE TITLE
Translate article to Spanish

### ISSUE THREAD

**Issue by mgravitt** [hashed-io/hashed-substrate#52]

**Comment by AugustoLara** [comment]
Document translated to spanish. I'm not closing the issue since we are waiting on some technical details from @3yekn 

English Verison: https://docs.google.com/document/d/1bDswb619nkdL0xt41GEJEtyLcCOc3LO-M-dB2RdDr9s/edit
Spanish Version: https://docs.google.com/document/d/1DNHgONQrZfpG4f0f79n6pS9h9jUQQDW52OlWCw1TiJA/edit
